version: 0.2
phases: 
  pre_build: 
    commands: 
    - $(aws ecr get-login --region ap-northeast-1 --no-include-email)
  build: 
    commands: 
    - docker build -t -t cfml .
    - docker tag cfml:latest $REPOSITORY_URI:latest
  post_build: 
    commands: 
    - docker push $REPOSITORY_URI:latest